{
 "title": "coloRadio - Status",
 "description": "Displays most important status data",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Time", "type": "grafana-clock-panel", "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 } },
  {
   "title": "Silence Detect",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Coloradio_GPIOs_status{gpioName=\"SD1 Master Alarm\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Silence Detect",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "Coloradio_GPIOs_status{gpioName=\"SD1 Master Alarm\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All streams",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Coloradio_Streams_listener_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All streams",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "Coloradio_Streams_listener_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stream Volume (dB)",
   "type": "timeseries",
   "description": "Stream Volume of Coloradio Stream in dB",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "Coloradio_Streams_volume{streamName=\"https://streaming.fueralle.org/coloradio_48.aac\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}