{
 "title": "coloRadio - Status Detail",
 "description": "Displays status of Silence Detection and Audio Router",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "SD1 Main Alarm",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Coloradio_GPIOs_status{gpioName=\"SD1 Master Alarm\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SD1 Main Alarm",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "Coloradio_GPIOs_status{gpioName=\"SD1 Master Alarm\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "KS In 04 - NC",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Coloradio_GPIOs_status{gpioName=\"KS In 04 - NC\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "KS In 05 - NC",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Coloradio_GPIOs_status{gpioName=\"KS In 05 - NC\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "KS In 06 - NC",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Coloradio_GPIOs_status{gpioName=\"KS In 06 - NC\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SD1 Aux Alarm",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Coloradio_GPIOs_status{gpioName=\"SD1 Aux Alarm\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SD1 Aux Alarm",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "Coloradio_GPIOs_status{gpioName=\"SD1 Aux Alarm\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "KS In 07 - NC",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Coloradio_GPIOs_status{gpioName=\"KS In 07 - NC\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "KS In 08 - NC",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Coloradio_GPIOs_status{gpioName=\"KS In 08 - NC\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "KS In 09 - NC",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Coloradio_GPIOs_status{gpioName=\"KS In 09 - NC\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "KS In 01 - Studio Grün",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Coloradio_GPIOs_status{gpioName=\"KS In 01 - Studio Grün\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "KS In 01 - Studio Grün",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "Coloradio_GPIOs_status{gpioName=\"KS In 01 - Studio Grün\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "KS In 10 - NC",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Coloradio_GPIOs_status{gpioName=\"KS In 10 - NC\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "KS In 02 - Studio Rot",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Coloradio_GPIOs_status{gpioName=\"KS In 02 - Studio Rot\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "KS In 03 - Studio Rot",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "Coloradio_GPIOs_status{gpioName=\"KS In 02 - Studio Rot\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "KS In 03 - Studio Gelb",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Coloradio_GPIOs_status{gpioName=\"KS In 03 - Studio Gelb\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "KS In 03 - Studio Gelb",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "Coloradio_GPIOs_status{gpioName=\"KS In 03 - Studio Gelb\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}