{
 "title": "coloRadio - Stream Volume Details",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Stream Volume Internet (dB)",
   "type": "timeseries",
   "description": "Stream Volume of coloRadio Internet Stream in dB",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "Coloradio_Streams_volume{streamName=\"https://streaming.fueralle.org/coloradio_48.aac\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stream Volume DAB+ Contrib A (dB)",
   "type": "timeseries",
   "description": "Stream Volume of coloRadio DAB+ Contribution Stream A in dB",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "Coloradio_Streams_volume{streamName=\"http://streamer-a.intern.coloradio.de:8000/coloradio-a.mp3\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stream Volume DAB+ Contrib B(dB)",
   "type": "timeseries",
   "description": "Stream Volume of coloRadio DAB+ Contribution Stream B in dB",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "Coloradio_Streams_volume{streamName=\"http://streamer-b.intern.coloradio.de:8000/coloradio-b.mp3\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}