{
 "title": "Coloradio - Stream Details",
 "description": "Displays listeners of Coloradio streams per stream and over time",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "All streams",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Coloradio_Streams_listener_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All streams",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "Coloradio_Streams_listener_count",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Time", "type": "grafana-clock-panel", "gridPos": { "h": 7, "w": 6, "x": 16, "y": 0 } },
  {
   "title": "MP3 160kBit/s",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Coloradio_Streams_listener_count{streamName=\"MP3 - 160kBit/s\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MP3 160kBit/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "Coloradio_Streams_listener_count{streamName=\"MP3 - 160kBit/s\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AAC 48kBit/s",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Coloradio_Streams_listener_count{streamName=\"AAC - 48kBit/s\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AAC 48 kBit/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "Coloradio_Streams_listener_count{streamName=\"AAC - 48kBit/s\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MP3 56kBit/s",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Coloradio_Streams_listener_count{streamName=\"MP3 - 56kBit/s\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MP3 56kBit/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "Coloradio_Streams_listener_count{streamName=\"MP3 - 56kBit/s\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ogg 160kBit/s",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Coloradio_Streams_listener_count{streamName=\"Ogg - 160kBit/s\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ogg 160kBit/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 4, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "Coloradio_Streams_listener_count{streamName=\"Ogg - 160kBit/s\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}